org: aadiupa
app: aws-python
service: aws-python

frameworkVersion: '2'

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  region: ap-south-1
  memorySize: 128
  timeout: 3

functions:
  - CreateTableAddRecordsAndRead:
      handler: app.handler
      reservedConcurrency: 5
      role: arn:aws:iam::612053565767:role/lambda-rds
      onError: arn:aws:sqs:ap-south-1:612053565767:serverless
      vpc:
        securityGroupIds:
          - sg-0f2772d23d5667429
        subnetIds:
          - subnet-050176daeaaf4ca7e
      events:
        s3:
          bucket: terraformadityabackend
          event: s3:ObjectCreated:*                


  - CreateTableAddRecordsAndRead2:
      handler: app.handler
      reservedConcurrency: 5
      role: arn:aws:iam::612053565767:role/lambda-rds
      vpc:
        securityGroupIds:
          - sg-0f2772d23d5667429
        subnetIds:
          - subnet-0c93594d51e8faf9f
      events:      
        sqs:
            arn: arn:aws:sqs:ap-south-1:612053565767:serverless-deadletter
            batchSize: 10
            maximumBatchingWindow: 10
            enabled: true


  - CreateTableAddRecordsAndRead3:
      handler: app.handler
      reservedConcurrency: 5
      role: arn:aws:iam::612053565767:role/lambda-rds
      vpc:
        securityGroupIds:
          - sg-0f2772d23d5667429
        subnetIds:
          - subnet-0b9ada5c7e8c135b1
